export const popupProfileEdit = document.querySelector('#popup-edit');
export const popupProfileEditCloseBtn = popupProfileEdit.querySelector('.popup__close-btn'); //Кнопка закрытия попапа
export const profileEditForm = popupProfileEdit.querySelector('.popup__form');
export const popupPlaceAdd = document.querySelector('#popup-add');
export const popupPlaceAddCloseBtn = popupPlaceAdd.querySelector('.popup__close-btn'); //Кнопка закрытия попапа
export const placeAddForm = popupPlaceAdd.querySelector('.popup__form');
export const popupZoom = document.querySelector('#popup-zoom');
export const popupZoomCloseBtn = popupZoom.querySelector('.popup__close-btn'); //Кнопка закрытия попапа
export const profileName = document.querySelector('.profile__name');
export const profileJob = document.querySelector('.profile__job');
export const popupProfileEditNameInput = document.querySelector('#popup-edit-input-name'); //Поле ввода имени
export const popupProfileEditJobInput = document.querySelector('#popup-edit-input-job'); //Поле ввода профессии
export const popupPlaceAddNameInput = document.querySelector('#popup-add-input-name'); //Поле ввода имени
export const popupPlaceAddLinkInput = document.querySelector('#popup-add-input-link'); //Поле ввода ссылки на изображение
export const profileEditBtn = document.querySelector('.profile__edit-btn'); //Кнопка редактирования профиля
export const placeAddBtn = document.querySelector('.profile__add-btn'); //Кнопка добавления места
export const gallery = document.querySelector('.gallery');
export const zoomPic = document.querySelector('.popup__zoom-pic');
export const zoomDesc = document.querySelector('.popup__desc');